export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_ERROR = "GET_ITEMS_ERROR";
export const SET_BOOKS_PER_AUTHOR = "SET_BOOKS_PER_AUTHOR";
export const SET_AUTHORS_IDS = "SET_AUTHORS_IDS";
export const SET_ACTIVE_AUTHOR = "SET_ACTIVE_AUTHOR";
