export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_DONE = "GET_ITEMS_DONE";
export const GET_ITEMS_ERROR = "GET_ITEMS_ERROR";
export const ASSIGN_AUTHORS = "ASSIGN_AUTHORS";
export const SET_AUTHOR_NAME = "SET_AUTHOR_NAME";
export const SET_BOOKS_PER_AUTHOR = "SET_BOOKS_PER_AUTHOR";
export const SET_CURRENT_AUTHOR = "SET_CURRENT_AUTHOR";
