export const LOAD_ITEMS = "LOAD_ITEMS";
export const UPDATE_FILTER = "UPDATE_FILTERS";
export const FILTER_ITEMS = "FILTER_ITEMS";
export const CLEAR_FILTER = "CLEAR_FILTER";
export const UPDATE_GIFT_FILTER = "UPDATE_GIFT_FILTER";
export const FILTER_GIFTS = "FILTER_GIFTS";
export const CLEAR_GIFT_FILTER = "CLEAR_GIFT_FILTER";
