export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_ERROR = "GET_ITEMS_ERROR";
export const GET_SINGLE_ITEM_START = "GET_SINGLE_ITEM_START";
export const GET_SINGLE_ITEM_SUCCESS = "GET_SINGLE_ITEM_SUCCESS";
export const GET_SINGLE_ITEM_ERROR = "GET_SINGLE_ITEM_ERROR";
