export const SIDEBARNAV_OPEN = "SIDEBARNAV_OPEN";
export const SIDEBARNAV_CLOSE = "SIDEBARNAV_CLOSE";
export const SIDEBAR_AUTHORS_OPEN = "SIDEBAR_AUTHORS_OPEN";
export const SIDEBAR_AUTHORS_CLOSE = "SIDEBAR_AUTHORS_CLOSE";
