export const SIDEBARNAV_OPEN = "SIDEBARNAV_OPEN";
export const SIDEBARNAV_CLOSE = "SIDEBARNAV_CLOSE";
export const SIDEBAR_BOOKS_OPEN = "SIDEBAR_BOOKS_OPEN";
export const SIDEBAR_BOOKS_CLOSE = "SIDEBAR_BOOKS_CLOSE";
export const SIDEBAR_AR_OPEN = "SIDEBAR_AR_OPEN";
export const SIDEBAR_AR_CLOSE = "SIDEBAR_AR_CLOSE";
