export const LOAD_INITIATED = "LOAD_INITIATED";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
export const LOAD_AUTHORS = "LOAD_AUTHORS";
export const SET_INITIAL_AUTHOR = "SET_INITIAL_AUTHOR";
export const UPDATE_AUTHOR = "UPDATE_AUTHOR";
export const SET_IMAGES = "SET_IMAGES";
