export const LOAD_INITIATED = "LOAD_INITIATED";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
export const LOAD_AUTHORS = "LOAD_AUTHORS";
export const HANDLE_AUTHORS = "HANDLE_AUTHORS";
export const ADD_AUTHOR_SPOT = "ADD_AUTHOR_SPOT";
export const SET_IMAGES = "SET_IMAGES";
export const UPDATE_BOOK = "UPDATE_BOOK";
