export const UPDATE_VALUE = "UPDATE_VALUE";
export const LOAD_VALUE = "LOAD_VALUE";
export const LOAD_ARRAY = "LOAD_ARRAY";
export const LOAD_INITIATED = "LOAD_INITIATED";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
export const LOAD_SECONDARY_ARRAY = "LOAD_SECONDARY_ARRAY";
